#Log4j2配置
logging:
  config: classpath:config/log4j2.xml

#Spring配置
spring:
    ## 多环境配置
    profiles:
        active: dev

    #数据库配置
    datasource:
        name: itender
        url: jdbc:mysql://${db.ip}:3306/${db.name}?useUnicode=true&characterEncoding=utf-8
        username: ${db.username}
        password: ${db.password}

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        initialSize: 1
        maxActive: 20
        maxWait: 30000
        minIdle: 1
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        validationQuery: "SELECT 'x'"
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 30000
        keepAlive: true

    #JPA配置
    jpa:
      hibernate:
        ddl-auto: update
      open-in-view: true

    #freemarker配置
    freemarker:
      allow-request-override: false # 设置是否允许HttpServletRequest属性重写（隐藏）控制器生成同名的模型属性。
      allow-session-override: false # 设置是否允许HttpSession属性重写（隐藏）控制器生成同名的模型属性。
      cache: false # 启用模板缓存。
      charset: UTF-8 # 编码。
      check-template-location: true # 检查模板位置是否存在。
      content-type: text/html
      enabled: true # 启用MVC视图解析。
      expose-request-attributes: false # 设置是否所有请求属性应与模板合并之前添加到模型。
      expose-session-attributes: false # 设置是否所有HttpSession属性应该与模板合并之前添加到模型。
      expose-spring-macro-helpers: true
      prefer-file-system-access: true # 模板加载文件系统访问。文件系统访问允许对模板更改进行热检测。
      prefix:
      request-context-attribute:
      suffix: .ftl # 视图名后缀名
      template-loader-path: classpath:/templates/ # 模板路径的分隔列表。